<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mono.Cecil" Version="0.11.4" />
    <PackageReference Include="MonoMod" Version="22.7.31.1" />
    <PackageReference Include="MonoMod.RuntimeDetour" Version="22.7.31.1" />
    <PackageReference Include="MonoMod.RuntimeDetour.HookGen" Version="22.7.31.1" GeneratePathProperty="true" />
    <PackageReference Include="MonoMod.Utils" Version="22.7.31.1" />
  </ItemGroup>

  <Target Name="CopyHookGenExecutable" AfterTargets="Build">
    <Copy
      SourceFiles="$(PkgMonoMod_RuntimeDetour_HookGen)\lib\net452\MonoMod.RuntimeDetour.HookGen.exe"
      DestinationFolder="$(TargetDir)" />
  </Target>

</Project>
