<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>HATinstaller</AssemblyName>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">$(NETCoreSdkRuntimeIdentifier)</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationIcon>HAT.ico</ApplicationIcon>
    <LangVersion>11</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <PublishTrimmed>true</PublishTrimmed>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GitInfo" Version="3.6.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" GeneratePathProperty="true">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>all</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="NETStandard.Library" Version="2.0.3" GeneratePathProperty="true">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>all</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="MonoMod" Version="22.7.31.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="HAT.txt" LogicalName="HAT.txt">
      <Visible>false</Visible>
    </EmbeddedResource>
    <EmbeddedResource Include="HAT.ico" LogicalName="HAT.ico">
      <Visible>false</Visible>
    </EmbeddedResource>
    <EmbeddedResource Include="$(PkgMicrosoft_NETFramework_ReferenceAssemblies_net48)\build\.NETFramework\v4.8\*.dll">
      <LogicalName>FrameworkReferences/%(Filename)%(Extension)</LogicalName>
      <Visible>false</Visible>
    </EmbeddedResource>
    <EmbeddedResource Include="$(PkgNETStandard_Library)\build\netstandard2.0\ref\netstandard.dll"
                      LogicalName="FrameworkReferences/Facades/netstandard.dll">
      <Visible>false</Visible>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Plugin\FEZ.HAT.mm.csproj">
      <SkipGetTargetFrameworkProperties>true</SkipGetTargetFrameworkProperties>
    </ProjectReference>
    <EmbeddedResource Include="..\Plugin\bin\$(Configuration)\HAT.zip"
                      LogicalName="HAT.zip"
                      Condition="Exists('..\Plugin\bin\$(Configuration)\HAT.zip')">
      <Visible>false</Visible>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="NETRuntime.targets;ZIPHat.targets">
      <Visible>false</Visible>
    </None>
  </ItemGroup>

  <Import Project="NETRuntime.targets" />
  <Import Project="ZIPHat.targets" />

</Project>
