<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>HATinstaller</AssemblyName>
    <OutputType>Exe</OutputType>
    <LangVersion>11</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ApplicationIcon>HAT.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
	<!-- these are needed for newer .NET version -->
    <PackageReference Include="System.Security.Permissions" Version="8.0.0"/>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0"/>
    <PackageReference Include="System.Threading.AccessControl" Version="8.0.0"/>
    <PackageReference Include="System.Drawing.Common" Version="8.0.0"/>
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="8.0.0"/>
    <PackageReference Include="System.CodeDom" Version="8.0.0"/>
    <PackageReference Include="System.IO.Ports" Version="8.0.0"/>
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="8.0.0"/>
    <PackageReference Include="System.Security.Cryptography.Xml" Version="8.0.0"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AsmResolver" Version="6.0.0-rc.1"/>
    <PackageReference Include="AsmResolver.PE" Version="6.0.0-rc.1"/>
    <PackageReference Include="AsmResolver.PE.Win32Resources" Version="6.0.0-rc.1"/>
    <PackageReference Include="GitInfo" Version="3.6.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="MonoMod" Version="22.7.31.1"/>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="HAT.txt" LogicalName="HAT.txt"/>
    <EmbeddedResource Include="HAT.sh" LogicalName="HAT.sh"/>
    <EmbeddedResource Include="HAT.ico" LogicalName="HAT.ico"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Plugin\FEZ.HAT.mm.csproj">
      <SkipGetTargetFrameworkProperties>true</SkipGetTargetFrameworkProperties>
    </ProjectReference>
  </ItemGroup>

  <!-- Rider design-time: resolve ThisAssembly even before HAT.zip exists -->
  <ItemGroup>
    <EmbeddedResource Include="..\Plugin\bin\$(Configuration)\HAT.zip" LogicalName="HAT.zip"
                      Condition="Exists('..\Plugin\bin\$(Configuration)\HAT.zip')"/>
  </ItemGroup>

  <Import Project="ZIPHat.targets"/>

</Project>